#!/bin/bash

cp=$0
if [ "$TERM" = "cygwin" ] || [ "$OSTYPE" = "cygwin" ] ; then
	cp=$(cygpath -u $cp)
fi
cp=${cp%/*}

if [ $# = 0 ] ; then
	cd $cp
	for f in cases/test*.zuss cases/issue*.zuss; do
		fcss=${f#*/}
		echo check $fcss
		fcss=${fcss%.zuss}.css
		./zuss $f > /tmp/$fcss
		diff cases/$fcss /tmp/$fcss > /dev/null
		if [ $? = 0 ] ; then
			echo success
		else
			echo Something different: cases/$fcss /tmp/$fcss 
		fi
	done
else
	cd $cp
	for f in cases/$*; do
		./zuss $f.zuss
	done
fi
