#!/bin/bash

cp=$0
if [ "$TERM" = "cygwin" ] ; then
	cp=$(cygpath -u $cp)
fi
cp=${cp%/*}
echo $cp

if [ $# = 0 ] ; then
	cd $cp
	for f in cases/*.zuss; do
		./zuss $f
	done
else
	cd $cp
	for f in cases/$*; do
		./zuss $f.zuss
	done
fi
